#define PAUSE_TYPE_OTHERS	1
#define PAUSE_TYPE_SELF		2

#define	MEDIA_PLAYER_FOOBAR	1
#define MEDIA_PLAYER_WINAMP	2
#define MEDIA_PLAYER_WMP	3
#define MEDIA_PLAYER_ITUNES 4
#define MEDIA_PLAYER_RHAPSODY 5
#define MEDIA_PLAYER_SPOTIFY 6